# Generated by Django 5.1.4 on 2025-01-12 11:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_cv_job_alter_cv_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cv',
            name='job',
            # field=models.ForeignKey(default=datetime.datetime(2025, 1, 12, 11, 10, 38, 152997, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
            preserve_default=False,
        ),
    ]
