# Generated by Django 5.1.4 on 2025-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_contactmessage_alter_cv_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='accept_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cv',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
