# Generated by Django 5.1.4 on 2025-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_cv_accept_terms_cv_age_cv_phone_cv_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], default='Full-time', max_length=20),
        ),
    ]
