# Generated by Django 5.1.4 on 2025-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jobs/'),
        ),
    ]
