# Generated by Django 5.1.4 on 2025-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='minimumqualification',
            field=models.CharField(default='High School', max_length=255),
        ),
    ]
