# Generated by Django 5.1.4 on 2025-01-27 06:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_minimumqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='minimumqualification',
            field=ckeditor.fields.RichTextField(default='High School'),
        ),
    ]
