# Generated by Django 5.1.4 on 2025-01-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_minimumqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='minimumqualification',
            field=models.TextField(default="• Bachelor's Degree\n• 2+ years of experience\n• Strong communication skills"),
        ),
    ]
